#!/bin/sh
killall sxhkd; sxhkd &
killall picom; picom -b --experimental-backends &
bspc monitor -d 1
bspc monitor -a 2 3 4 5 6 7 8 9 10
killall polybar; polybar default &
dunst &
mpd &

# config
bspc config border_width 3
bspc config window_gap 16
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config swallow_first_click true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config normal_border_color "#282828"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#fe8019"

# Window rules
bspc rule -a mpv state=floating
bspc rule -a firefox desktop="^2"
bspc rule -a spotify desktop="^10"


feh --bg-scale ~/Pictures/wallpapers/wallpaper.jpg

# Mouse Touchpad settings
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1

# Keyboard settings
setxkbmap -layout us,ar
setxkbmap -option 'grp:alt_shift_toggle'

#bspwm-blurwall &

bspc monitor -d I II III IV V VI VII VIII IX X



