#!/bin/sh

case $BLOCK_BUTTON in
	2) notify-send "$(/usr/bin/pacman -Qu|awk '{print $1}')" ;;
	3) pgrep -x dunst >/dev/null && notify-send "<b>Upgrade module:</b>
📦: number of upgradable packages
- Left click to upgrade packages
- Middle click to show upgradable packages" ;;
esac


pacman -Qu| wc -l|sed -e "s/^0$//g"
